### ISSUE TITLE
Suspicious string

### ISSUE THREAD

**Issue by B0und** [mahloola/osuCollector-frontend#3]
https://github.com/mahloola/osuCollector-frontend/blob/583cb5533ff2e2ce47df5ded7cca56d022265786/src/App.js#L36
 Is it alright to keep this public?
I haven`t had the chance to work with stripe much yet, but long strings like these are usually some tokens/secrets that should be hidden in a .env

**Comment by FunOrange** [comment]
Don't worry, the "pk" stands for public key. This one is fine to put in source code
